### ISSUE TITLE
Add shell one-line install

### ISSUE THREAD

**Issue by jpillora** [ogham/dog#16]
I often setup new machines and want to quickly grab Go/Rust binaries from github, so I wrote a web service to do this https://github.com/jpillora/installer (e.g. `curl https://i.jpillora.com/ogham/dog!`). This seems like a common thing people do (e.g. https://github.com/jpillora/chisel#install see binary download count).

You might not be in favour shell one liners, completely understand, feel free to close. Also, awesome project! This will definitely be replacing `host` / `dig`, just like `exa` has replaced `ls` 😁

**Comment by ogham** [comment]
Hi, and thanks! I'm afraid you have my stance on shell one-liners correct — when dealing with downloading binaries from the internet and running them, I really want to limit the installation instructions to using official package managers and long-lived distributors, because the security risk is so high.
