### ISSUE TITLE
installing via homebrew on ubuntu 20.04 fails

### ISSUE THREAD

**Issue by sagor999** [ogham/dog#22]
Not sure if this is something that you might fix or if this is an issue with homebrew somehow, but trying to install dog via homebrew:
`brew install dog` on ubuntu 20.04, getting this error:
```
==> Downloading https://github.com/ogham/dog/archive/v0.1.0.tar.gz
Already downloaded: /home/pavel/.cache/Homebrew/downloads/e9869860b4b74bd1955a7e4be363a6bbd20d683ca8b4cf4942938e6567865c15--dog-0.1.0.tar.gz
==> cargo install
Last 15 lines from /home/pavel/.cache/Homebrew/Logs/dog/01.cargo:
  If you're in a situation where you think the directory *should* be found
  automatically, please open a bug at https://github.com/sfackler/rust-openssl
  and include information about your system as well as this message.

  $HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.58

  ', /home/pavel/.cache/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.58/build/find_normal.rs:157:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dog v0.1.0 (/tmp/dog-20201110-1700102-b2dqt0/dog-0.1.0)`, intermediate artifacts can be found at `/tmp/dog-20201110-1700102-b2dqt0/dog-0.1.0/target`

Caused by:
  build failed

READ THIS: https://docs.brew.sh/Troubleshooting
```

**Comment by ogham** [comment]
This is specifically an issue with Homebrew on Linux. dog depends on a TLS library (`native_tls`) that uses the system functions on Windows and macOS, but openssl on other platforms, so the list of dependencies are _not the same_ between the two platforms. I'm guessing that the formula was written with only Homebrew Mac in mind.

I believe the missing packages on Ubuntu you'll need to install are `libssl-dev`, and possibly `pkg-config`, but I'm not sure about the last one, you'll have to try it.

So you'll have to chase this up with the Homebrew folks I'm afraid — see if there's a way to specify a Linux-only dependency.

**Comment by sslavic** [comment]
I can confirm that manually installing dependencies:
```
sudo apt-get install pkg-config libssl-dev
```
works as temp mitigation. It beats though the purpose of using Homebrew as package manager for `dog` on Linux, if one has to use another package manager to install the dependencies. Ideally same package manager should work for both `dog` and its dependencies.

Homebrew folks own governance but not the maintenance of the contributed formulas.

From governance perspective, it is fine for a project like dog to choose to support just macOS in the contributed formula, but it's project specific decision which OS-es to support and maintain with the formula.

Also every new `dog` project release typically should create PR to update its formula in https://github.com/Homebrew/homebrew-core, ideally automated as part of the release process.

So @ogham please consider reopening this issue for `dog` Homebrew formula Linux support, and create a separate issue for (automating or documenting) formula updates with project releases.

@vladimyr since you contributed initial formula via https://github.com/Homebrew/homebrew-core/pull/64389 do you maybe know how to add Linux support too? From other rust/cargo formulas and docs, see https://github.com/Homebrew/homebrew-core/pull/43853/files and https://docs.rs/openssl/0.10.30/openssl/#manual, it seems a dependency on `openssl` has to be added in formula and `OPENSSL_DIR` environment variable has to be set before `cargo install` step. Would that work for both macOS and Linux?

**Comment by vladimyr** [comment]
> I'm guessing that the formula was written with only Homebrew Mac in mind.

Yes, I don't use _linuxbrew_ and Linux in general so I didn't test it there 🤷 

> Also every new `dog` project release typically should create PR to update its formula in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core), ideally automated as part of the release process.

Which is exactly what I did here using Github actions https://github.com/ogham/dog/pull/24

> @vladimyr since you contributed initial formula via [Homebrew/homebrew-core#64389](https://github.com/Homebrew/homebrew-core/pull/64389) do you maybe know how to add Linux support too? From other rust/cargo formulas and docs, see [Homebrew/homebrew-core#43853 (files)](https://github.com/Homebrew/homebrew-core/pull/43853/files) and [docs.rs/openssl/0.10.30/openssl/#manual](https://docs.rs/openssl/0.10.30/openssl/#manual), it seems a dependency on `openssl` has to be added in formula and `OPENSSL_DIR` environment variable has to be set before `cargo install` step. Would that work for both macOS and Linux?

As I said earlier, my Linux days are long gone, and back in the day, I didn't use linuxbrew. After reading this, I actually tried installing linuxbrew on my [tildeverse](http://ctrl-c.club/) account, but my attempt failed miserably, resulting in brew complaining about the too old version of curl & git being provided.
Anyhow, this is what I had in mind:
```diff
diff --git a/Formula/dog.rb b/Formula/dog.rb
index dbc219e7b8..6510d91e7a 100644
--- a/Formula/dog.rb
+++ b/Formula/dog.rb
@@ -18,6 +18,11 @@ class Dog < Formula
   depends_on "pandoc" => :build
   depends_on "rust" => :build
 
+  on_linux do
+    depends_on "pkg-config" => :build
+    depends_on "openssl@1.1"
+  end
+
   def install
     system "cargo", "install", *std_cargo_args
     bash_completion.install "completions/dog.bash" => "dog"
```
I'm obviously not able to verify it so @sslavic let me know does it help 🤞

**Comment by vladimyr** [comment]
I don't give up that easily... I spinned vagrant box with Arch, applied the diff and here we have it, fully working linked against brewed openssl:
```
vagrant in arch in ~ took 2s
❯ ldd $(which dog) && brew test -v dog
	linux-vdso.so.1 (0x00007fff22784000)
	libssl.so.1.1 => /home/linuxbrew/.linuxbrew/lib/libssl.so.1.1 (0x00007f966ec9a000)
	libcrypto.so.1.1 => /home/linuxbrew/.linuxbrew/lib/libcrypto.so.1.1 (0x00007f966e7b8000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f966e7ac000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f966e78a000)
	libgcc_s.so.1 => /home/linuxbrew/.linuxbrew/lib/libgcc_s.so.1 (0x00007f966e573000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f966e3aa000)
	/home/linuxbrew/.linuxbrew/lib/ld.so => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f966efd9000)
==> Testing dog
==> /home/linuxbrew/.linuxbrew/Cellar/dog/0.1.0/bin/dog dns.google A --seconds --color=never
```
PR is sent → https://github.com/Homebrew/linuxbrew-core/pull/21710
