### ISSUE TITLE
`dog` command collides with sheepdog

### ISSUE THREAD

**Issue by NotAFile** [ogham/dog#27]
The `sheepdog` project, which is officially deprecated, but still depended on by a number of tools including libvirt-lxc and Gnome Boxes and hence preinstalled on a number of linux systems also uses `dog` as a command name. This can be seen with e.g:

```bash
$ sudo dnf provides dog
sheepdog-1.0.1-13.fc33.x86_64 : The Sheepdog distributed storage system for KVM/QEMU
Repo        : @System
Matched from:
Filename    : /usr/bin/dog
```

I'm not sure it's worth changing your name over collision with a project that is deprecated anyway, however this is still an issue that is good to be aware of as it will likely affect users until the dependencies on Sheepdog are removed from those projects upstream.

**Comment by ogham** [comment]
I _may_ end up changing the name at some point, but if I do, it won't be for this reason — deprecated or not, this sort of problem comes with the territory of packaging projects for an OS that favours short command names!

The preferred solution seems to be changing the name of the package and binary so that they don't conflict, such as Debian renaming the [bat](https://github.com/sharkdp/bat) project to [batcat](https://packages.ubuntu.com/groovy/amd64/bat/filelist) because the former was taken. And if you're installing it yourself, you can simply rename the binary without it affecting anything. I don't mind if people do this, and if enough people bring it up, I can add some instructions to the README or something.
