### ISSUE TITLE
Maybe add a special DNS record type ALL

### ISSUE THREAD

**Issue by igrmk** [ogham/dog#31]
Maybe add a special DNS record type ALL to query all known types?
It would be very handy feature

**Comment by ogham** [comment]
I'm deliberately avoiding this functionality because there are a _lot_ of record types, and picking which types to include in the list is something that should be left up to the user.

See [this comment](https://github.com/ogham/dog/issues/8#issuecomment-727575969) for a much longer explanation (point 3 pertains to an `--all` flag).

**Comment by svenstaro** [comment]
I think a `--common`/`-all` (or similar) flag could still work as it would more or less cover my original request and this one. It doesn't really have to get _ALL_ entries, just the ones people usually care about.
